component:
  master: true
  metanode: true
  datanode: false
  objectnode: false
  client: false
  csi: false
  monitor: false
  ingress: false
  blobstore_clustermgr: false
  blobstore_blobnode: false
  blobstore_proxy: false
  blobstore_scheduler: false
  blobstore_access: false

image:
  server: docker.17usoft.com/lhhdz/cubefs/cfs-server:dev
  pull_policy: "Always"
master:
  # The replicas of master component, at least 3, recommend to be an odd number
  replicas: 3
  # Cluster name
  cluster: jfscubefs-dev
  # NodeSelector
  nodeSelector:
    "component.cubefs.io/master": "enabled"
  path:
    log: /data/logs/infss.cubefs.master
  tolerations: [ ]
  host: master.cubefs.com
  log_level: error
  retain_logs: 2000
  # Master service http port
  port: 17010
  # Master golang pprof port
  prof: 17020
  exporter_port: 9500
  # Reserved memory in bytes for each metanode, if available memory less than this value, the metanode will be unwritable
  metanode_reserved_mem: "67108864"
  legacy_data_media_type: 1
  resources:
    enabled: true
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "8Gi"
      cpu: "4"

metanode:
  # NodeSelector for metanode daemonset
  nodeSelector:
    "component.cubefs.io/metanode": "enabled"
  path:
    log: /data/logs/infss.cubefs.meta
  tolerations: [ ]
  log_level: error
  # Total memory metanode can use, recommended to be configured
  # as 80% of physical machine memory
  total_mem: "8196000000"
  port: 17210
  prof: 17220
  raft_heartbeat: 17230
  raft_replica: 17240
  exporter_port: 9510
  resources:
    enabled: true
    requests:
      memory: "1Gi"
      cpu: "200m"
    limits:
      memory: "8Gi"
      cpu: "4"
  # Similar to datanode.config_override, all the config
  # listed here will be merge into metanode config file.
  config_override: |
    {
    }