# Select which component to install
component:
  master: true
  datanode: false
  metanode: true
  objectnode: false
  client: false
  csi: false
  monitor: false
  ingress: false
  blobstore_clustermgr: false
  blobstore_blobnode: false
  blobstore_proxy: false
  blobstore_scheduler: false
  blobstore_access: false

image:
  server: docker.17usoft.com/lhhdz/cubefs/cfs-server:v3.5.0

master:
  host: master.cubefs.com
  log_level: warn
  # Cluster name
  cluster: dev
  # Reserved memory in bytes for each metanode, if available memory less than this value, the metanode will be unwritable
  metanode_reserved_mem: "67108864"
  resources:
    enabled: false
    requests:
      memory: "8Gi"
      cpu: "2000m"
    limits:
      memory: "32Gi"
      cpu: "8000m"
  # The replicas of master component, at least 3, recommend to be an odd number
  replicas: 3

metanode:
  # NodeSelector for metanode daemonset
  nodeSelector:
    "component.cubefs.io/metanode": "enabled"
  tolerations: [ ]
  log_level: warn
  # Total memory metanode can use （256GiB）, recommended to be configured
  # as 80% of physical machine memory
  total_mem: "26843545600"
  resources:
    enabled: true
    requests:
      memory: "32Gi"
      cpu: "2000m"
    limits:
      memory: "128Gi"
      cpu: "8000m"
  # Similar to datanode.config_override, all the config
  # listed here will be merge into metanode config file.
  config_override: |
    {
    }

consul:
  port: 8500
  replicas: 1
  external_address: ""